name: Simple CI CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Run Test
        run: echo "code checked successfully"

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 82.112.238.89

          username: root
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/deploy/ci-demo"
